### ISSUE TITLE
Compiling on Mac -- cargs directory missing

### ISSUE THREAD

**Issue by drf5n** [hayguen/mlpolygen#1]
I had an error using the README.rst instructions on a Mac since it was looking for/creating an empty cargs directory.

```
git clone git@github.com:hayguen/mlpolygen.git
cmake -S mlpolygen -B build_mlpolygen -DCMAKE_BUILD_TYPE=Release
cmake --build build_mlpolygen
```
gave me

```
...
CMake Error at CMakeLists.txt:66 (add_subdirectory):
  The source directory

    /Users/drf/junk/mlpolygen/cargs

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
...

```

My workaround was:

```
git clone git@github.com:hayguen/mlpolygen.git
cd mlpolygon
git clone git@github.com:likle/cargs.git
cd ..
cmake -S mlpolygen -B build_mlpolygen -DCMAKE_BUILD_TYPE=Release
cmake --build build_mlpolygen

```

... and it then compiled into build_mpolygen without error.

**Comment by hayguen** [comment]
looks, you missed the "--recursive" flag at "git clone", which is described in the README.
would you please try again? and report the result for mac

**Comment by drf5n** [comment]
I see.  I normally grab repositories with a `git clone ...` and then look at the repository locally.  I skipped over the re-clone advice.


This works without error:
```
git clone --recursive git@github.com:hayguen/mlpolygen.git
cmake -S mlpolygen -B build_mlpolygen -DCMAKE_BUILD_TYPE=Release
cmake --build build_mlpolygen 

```

And upon noticing that cargs is a submodule and reading https://git-scm.com/book/en/v2/Git-Tools-Submodules I found this works as well:

```
git clone --recursive git@github.com:hayguen/mlpolygen.git
cd mlpolygen
git submodule init
git submodule update
cd ..
cmake -S mlpolygen -B build_mlpolygen -DCMAKE_BUILD_TYPE=Release
cmake --build build_mlpolygen

```

**Comment by hayguen** [comment]
added a hint in the README
and also added a check with an appropriate error message in the CMakeLists.txt

**Comment by drf5n** [comment]
Thanks.  Closing.
