### ISSUE TITLE
Copyright (C) 2012 Gregory E. Allen lines

### ISSUE THREAD

**Issue by drf5n** [hayguen/mlpolygen#2]
You might add George Allen's 2012 copyright info from his bitbucket README.rst and then add your own, like:

```
 Copyright (C) 2012  Gregory E. Allen
 Copyright (C) 2021  Hayati Ayguen
```

I did think it was your work, when I hunted this code down based on Koopman's page at  http://users.ece.cmu.edu/~koopman/lfsr/

**Comment by hayguen** [comment]
you suggest to make it visible in the README?
in fact there's a copyright notice of Gergory Allen in the README .. but it is (somehow) hidden!

**Comment by hayguen** [comment]
have a look!

**Comment by drf5n** [comment]
Thanks.  I see it now.

I think it might have been hidden before because it looks like an .rst indented comment block.  (I don't know rst).

Thanks.
